# SwiftLint Configuration for SubscribeCoffieClean

# Paths to include in linting
included:
  - SubscribeCoffieClean/SubscribeCoffieClean

# Paths to exclude from linting
excluded:
  - Pods
  - SubscribeCoffieClean/SubscribeCoffieClean.xcodeproj
  - SubscribeCoffieClean/SubscribeCoffieCleanTests
  - SubscribeCoffieClean/SubscribeCoffieCleanUITests
  - build
  - derived_data
  - fastlane

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - todo

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - db

nesting:
  type_level:
    warning: 2
    error: 3

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use proper logging instead of print()"
    severity: warning
  
  no_force_cast:
    name: "No Force Cast"
    regex: "as!"
    message: "Avoid force casting, use optional casting instead"
    severity: warning

# Reporter type
reporter: "xcode"
